language: elixir

elixir:
  - 1.4.5
  - 1.5.1

notifications:
  recipients:
    - bruce.williams@cargosense.com
    - ben.wilson@cargosense.com

otp_release:
  - 19.2
  - 20.0

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, compile

script:
  - mix test
  - mix dialyzer
