name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.10'
            otp: '22'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-${{ github.sha }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Create dializer plts path
      run: mkdir -p priv/plts

    - name: Restore plts cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: plts-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-${{ github.sha }}
        restore-keys: |
          plts-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          plts-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install package dependencies
      run: mix deps.get

    - name: Remove compiled application files
      run: mix clean

    - name: Compile application
      run: mix compile
      env:
        MIX_ENV: test

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run unit tests
      run: mix test

    - name: Run unit tests with persistent_term backend
      run: mix test
      env:
        SCHEMA_PROVIDER: persistent_term

    - name: Run dialyzer
      run: mix dialyzer
